network:
  ethernets:
    enp0s3: # этот интерфейс используем для доступа с ноутбука
      dhcp4: true 
    enp0s8: # этот интерфейс настравиваем на передачу запросов
      dhcp4: false
      addresses: [192.168.4.100/24]
      routes:
        - to: [192.168.18.0/24]
        via: 192.168.4.1
  version: 2
  
  
  
